# Generated by Django 6.0.1 on 2026-02-03 22:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sample',
            options={'managed': False, 'ordering': ['sequence_number'], 'verbose_name': 'Образец', 'verbose_name_plural': 'Образцы'},
        ),
        migrations.CreateModel(
            name='SampleFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to='', verbose_name='Файл')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Исходное имя файла')),
                ('file_size', models.BigIntegerField(verbose_name='Размер файла (байты)')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='Описание')),
                ('sample', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='core.sample', verbose_name='Образец')),
                ('uploaded_by', models.ForeignKey(db_column='uploaded_by_id', on_delete=django.db.models.deletion.RESTRICT, related_name='uploaded_files', to=settings.AUTH_USER_MODEL, verbose_name='Загрузил')),
            ],
            options={
                'verbose_name': 'Файл образца',
                'verbose_name_plural': 'Файлы образцов',
                'db_table': 'sample_files',
                'ordering': ['-uploaded_at'],
                'managed': True,
            },
        ),
    ]
