-- ============================================================
-- CISIS — Полная схема базы данных
-- Версия: v3.13.0 (19 февраля 2026)
-- 
-- Использование:
--   Для развёртывания новой базы выполнить весь файл в pgAdmin
--   ПЕРЕД этим создать базу: CREATE DATABASE "CISIS";
--
-- После выполнения схемы нужно:
--   1. python manage.py migrate (создаст системные таблицы Django)
--   2. Заполнить справочники (laboratories, roles и т.д.)
-- ============================================================

--
-- PostgreSQL database dump
--


-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: prevent_user_deletion(); Type: FUNCTION; Schema: public; Owner: -
--

CREATE FUNCTION public.prevent_user_deletion() RETURNS trigger
    LANGUAGE plpgsql
    AS $$
BEGIN
    RAISE EXCEPTION '╨г╨┤╨░╨╗╨╡╨╜╨╕╨╡ ╨┐╨╛╨╗╤М╨╖╨╛╨▓╨░╤В╨╡╨╗╨╡╨╣ ╨╖╨░╨┐╤А╨╡╤Й╨╡╨╜╨╛! ╨Ш╤Б╨┐╨╛╨╗╤М╨╖╤Г╨╣╤В╨╡ ╨┤╨╡╨░╨║╤В╨╕╨▓╨░╤Ж╨╕╤О (is_active = FALSE)';
    RETURN NULL;
END;
$$;


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: accreditation_areas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.accreditation_areas (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    code character varying(20) NOT NULL,
    description text DEFAULT ''::text,
    is_active boolean DEFAULT true,
    is_default boolean DEFAULT false
);


--
-- Name: accreditation_areas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.accreditation_areas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: accreditation_areas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.accreditation_areas_id_seq OWNED BY public.accreditation_areas.id;


--
-- Name: auth_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group (
    id integer NOT NULL,
    name character varying(150) NOT NULL
);


--
-- Name: auth_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_group_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_group_permissions (
    id bigint NOT NULL,
    group_id integer NOT NULL,
    permission_id integer NOT NULL
);


--
-- Name: auth_group_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_group_permissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_group_permissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: auth_permission; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.auth_permission (
    id integer NOT NULL,
    name character varying(255) NOT NULL,
    content_type_id integer NOT NULL,
    codename character varying(100) NOT NULL
);


--
-- Name: auth_permission_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.auth_permission ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_permission_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: client_contacts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.client_contacts (
    id integer NOT NULL,
    client_id integer NOT NULL,
    full_name character varying(200) NOT NULL,
    "position" character varying(200) DEFAULT ''::character varying,
    phone character varying(50) DEFAULT ''::character varying,
    email character varying(255) DEFAULT ''::character varying,
    is_primary boolean DEFAULT false
);


--
-- Name: client_contacts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.client_contacts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: client_contacts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.client_contacts_id_seq OWNED BY public.client_contacts.id;


--
-- Name: clients; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.clients (
    id integer NOT NULL,
    name character varying(500) NOT NULL,
    inn character varying(12) DEFAULT ''::character varying,
    address text DEFAULT ''::text,
    is_active boolean DEFAULT true,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: clients_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.clients_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: clients_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.clients_id_seq OWNED BY public.clients.id;


--
-- Name: climate_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.climate_log (
    id integer NOT NULL,
    laboratory_id integer NOT NULL,
    measured_at timestamp without time zone NOT NULL,
    temperature numeric(5,1) NOT NULL,
    humidity numeric(5,1) NOT NULL,
    measured_by_id integer NOT NULL,
    notes text DEFAULT ''::text
);


--
-- Name: climate_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.climate_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: climate_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.climate_log_id_seq OWNED BY public.climate_log.id;


--
-- Name: contracts; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.contracts (
    id integer NOT NULL,
    client_id integer NOT NULL,
    number character varying(100) NOT NULL,
    date date NOT NULL,
    end_date date,
    status character varying(20) DEFAULT 'ACTIVE'::character varying NOT NULL,
    notes text DEFAULT ''::text
);


--
-- Name: contracts_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.contracts_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: contracts_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.contracts_id_seq OWNED BY public.contracts.id;


--
-- Name: django_admin_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_admin_log (
    id integer NOT NULL,
    action_time timestamp with time zone NOT NULL,
    object_id text,
    object_repr character varying(200) NOT NULL,
    action_flag smallint NOT NULL,
    change_message text NOT NULL,
    content_type_id integer,
    user_id bigint NOT NULL,
    CONSTRAINT django_admin_log_action_flag_check CHECK ((action_flag >= 0))
);


--
-- Name: django_admin_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_admin_log ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_admin_log_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_content_type; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_content_type (
    id integer NOT NULL,
    app_label character varying(100) NOT NULL,
    model character varying(100) NOT NULL
);


--
-- Name: django_content_type_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_content_type ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_content_type_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_migrations (
    id bigint NOT NULL,
    app character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    applied timestamp with time zone NOT NULL
);


--
-- Name: django_migrations_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.django_migrations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.django_migrations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: django_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.django_session (
    session_key character varying(40) NOT NULL,
    session_data text NOT NULL,
    expire_date timestamp with time zone NOT NULL
);


--
-- Name: equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment (
    id integer NOT NULL,
    accounting_number character varying(50) NOT NULL,
    equipment_type character varying(20) NOT NULL,
    name character varying(200) NOT NULL,
    inventory_number character varying(50) NOT NULL,
    ownership character varying(20) DEFAULT 'OWN'::character varying NOT NULL,
    ownership_doc_number character varying(200) DEFAULT ''::character varying,
    manufacturer character varying(200) DEFAULT ''::character varying,
    year_of_manufacture integer,
    factory_number character varying(100) DEFAULT ''::character varying,
    state_registry_number character varying(200) DEFAULT ''::character varying,
    technical_documentation text DEFAULT ''::text,
    intended_use character varying(200) DEFAULT ''::character varying,
    metrology_doc text DEFAULT ''::text,
    technical_specs text DEFAULT ''::text,
    software text DEFAULT ''::text,
    operating_conditions text DEFAULT ''::text,
    commissioning_info text DEFAULT ''::text,
    condition_on_receipt text DEFAULT ''::text,
    laboratory_id integer NOT NULL,
    status character varying(20) DEFAULT 'OPERATIONAL'::character varying NOT NULL,
    metrology_interval integer,
    modifications text DEFAULT ''::text,
    notes text DEFAULT ''::text,
    files_path character varying(500) DEFAULT ''::character varying,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    responsible_person_id integer,
    substitute_person_id integer
);


--
-- Name: equipment_accreditation_areas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment_accreditation_areas (
    id integer NOT NULL,
    equipment_id integer NOT NULL,
    accreditation_area_id integer NOT NULL
);


--
-- Name: equipment_accreditation_areas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.equipment_accreditation_areas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: equipment_accreditation_areas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.equipment_accreditation_areas_id_seq OWNED BY public.equipment_accreditation_areas.id;


--
-- Name: equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.equipment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: equipment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.equipment_id_seq OWNED BY public.equipment.id;


--
-- Name: equipment_maintenance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.equipment_maintenance (
    id integer NOT NULL,
    equipment_id integer NOT NULL,
    maintenance_date date NOT NULL,
    maintenance_type character varying(20) NOT NULL,
    document_name text DEFAULT ''::text,
    reason text DEFAULT ''::text,
    description text DEFAULT ''::text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    performed_by_id integer
);


--
-- Name: equipment_maintenance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.equipment_maintenance_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: equipment_maintenance_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.equipment_maintenance_id_seq OWNED BY public.equipment_maintenance.id;


--
-- Name: holidays; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.holidays (
    id integer NOT NULL,
    date date NOT NULL,
    name character varying(200) NOT NULL,
    is_working boolean DEFAULT false
);


--
-- Name: holidays_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.holidays_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: holidays_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.holidays_id_seq OWNED BY public.holidays.id;


--
-- Name: journal_columns; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.journal_columns (
    id integer NOT NULL,
    journal_id integer NOT NULL,
    code character varying(100) NOT NULL,
    name character varying(200) NOT NULL,
    is_active boolean DEFAULT true,
    display_order integer DEFAULT 0
);


--
-- Name: journal_columns_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.journal_columns_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: journal_columns_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.journal_columns_id_seq OWNED BY public.journal_columns.id;


--
-- Name: journals; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.journals (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(200) NOT NULL,
    is_active boolean DEFAULT true
);


--
-- Name: journals_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.journals_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: journals_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.journals_id_seq OWNED BY public.journals.id;


--
-- Name: laboratories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.laboratories (
    id integer NOT NULL,
    name character varying(200) NOT NULL,
    code character varying(10) NOT NULL,
    is_active boolean DEFAULT true,
    head_id integer,
    code_display character varying(10)
);


--
-- Name: laboratories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.laboratories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: laboratories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.laboratories_id_seq OWNED BY public.laboratories.id;


--
-- Name: permissions_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.permissions_log (
    id integer NOT NULL,
    changed_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    changed_by_id integer NOT NULL,
    target_user_id integer,
    role character varying(20) DEFAULT ''::character varying,
    journal_id integer NOT NULL,
    column_id integer,
    old_access_level character varying(10) NOT NULL,
    new_access_level character varying(10) NOT NULL,
    reason text DEFAULT ''::text,
    permission_type character varying(20) NOT NULL
);


--
-- Name: permissions_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.permissions_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: permissions_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.permissions_log_id_seq OWNED BY public.permissions_log.id;


--
-- Name: role_permissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.role_permissions (
    id integer NOT NULL,
    role character varying(20) NOT NULL,
    journal_id integer NOT NULL,
    column_id integer,
    access_level character varying(10) DEFAULT 'NONE'::character varying NOT NULL
);


--
-- Name: role_permissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.role_permissions_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: role_permissions_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.role_permissions_id_seq OWNED BY public.role_permissions.id;


--
-- Name: sample_auxiliary_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_auxiliary_equipment (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    equipment_id integer NOT NULL
);


--
-- Name: sample_auxiliary_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_auxiliary_equipment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_auxiliary_equipment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_auxiliary_equipment_id_seq OWNED BY public.sample_auxiliary_equipment.id;


--
-- Name: sample_files; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_files (
    id bigint NOT NULL,
    file character varying(500) NOT NULL,
    original_filename character varying(255) NOT NULL,
    file_size bigint NOT NULL,
    uploaded_at timestamp with time zone NOT NULL,
    description character varying(500) NOT NULL,
    sample_id bigint NOT NULL,
    uploaded_by_id bigint NOT NULL
);


--
-- Name: sample_files_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sample_files ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sample_files_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sample_manufacturing_auxiliary_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_manufacturing_auxiliary_equipment (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    equipment_id integer NOT NULL
);


--
-- Name: sample_manufacturing_auxiliary_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_manufacturing_auxiliary_equipment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_manufacturing_auxiliary_equipment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_manufacturing_auxiliary_equipment_id_seq OWNED BY public.sample_manufacturing_auxiliary_equipment.id;


--
-- Name: sample_manufacturing_measuring_instruments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_manufacturing_measuring_instruments (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    equipment_id integer CONSTRAINT sample_manufacturing_measuring_instrument_equipment_id_not_null NOT NULL
);


--
-- Name: TABLE sample_manufacturing_measuring_instruments; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.sample_manufacturing_measuring_instruments IS '╨б╨▓╤П╨╖╤М ╨╛╨▒╤А╨░╨╖╤Ж╨░ ╤Б╨╛ ╤Б╤А╨╡╨┤╤Б╤В╨▓╨░╨╝╨╕ ╨╕╨╖╨╝╨╡╤А╨╡╨╜╨╕╨╣ ╨┤╨╗╤П ╨╕╨╖╨│╨╛╤В╨╛╨▓╨╗╨╡╨╜╨╕╤П';


--
-- Name: sample_manufacturing_measuring_instruments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_manufacturing_measuring_instruments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_manufacturing_measuring_instruments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_manufacturing_measuring_instruments_id_seq OWNED BY public.sample_manufacturing_measuring_instruments.id;


--
-- Name: sample_manufacturing_operators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_manufacturing_operators (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: TABLE sample_manufacturing_operators; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.sample_manufacturing_operators IS '╨б╨▓╤П╨╖╤М ╨╛╨▒╤А╨░╨╖╤Ж╨░ ╤Б ╨╛╨┐╨╡╤А╨░╤В╨╛╤А╨░╨╝╨╕ ╨╕╨╖╨│╨╛╤В╨╛╨▓╨╗╨╡╨╜╨╕╤П (╨╝╨░╤Б╤В╨╡╤А╤Б╨║╨░╤П)';


--
-- Name: sample_manufacturing_operators_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_manufacturing_operators_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_manufacturing_operators_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_manufacturing_operators_id_seq OWNED BY public.sample_manufacturing_operators.id;


--
-- Name: sample_manufacturing_testing_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_manufacturing_testing_equipment (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    equipment_id integer NOT NULL
);


--
-- Name: TABLE sample_manufacturing_testing_equipment; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.sample_manufacturing_testing_equipment IS '╨б╨▓╤П╨╖╤М ╨╛╨▒╤А╨░╨╖╤Ж╨░ ╤Б ╨╕╤Б╨┐╤Л╤В╨░╤В╨╡╨╗╤М╨╜╤Л╨╝ ╨╛╨▒╨╛╤А╤Г╨┤╨╛╨▓╨░╨╜╨╕╨╡╨╝ ╨┤╨╗╤П ╨╕╨╖╨│╨╛╤В╨╛╨▓╨╗╨╡╨╜╨╕╤П';


--
-- Name: sample_manufacturing_testing_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_manufacturing_testing_equipment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_manufacturing_testing_equipment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_manufacturing_testing_equipment_id_seq OWNED BY public.sample_manufacturing_testing_equipment.id;


--
-- Name: sample_measuring_instruments; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_measuring_instruments (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    equipment_id integer NOT NULL
);


--
-- Name: sample_measuring_instruments_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_measuring_instruments_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_measuring_instruments_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_measuring_instruments_id_seq OWNED BY public.sample_measuring_instruments.id;


--
-- Name: sample_operators; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_operators (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    user_id integer NOT NULL
);


--
-- Name: sample_operators_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_operators_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_operators_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_operators_id_seq OWNED BY public.sample_operators.id;


--
-- Name: sample_standards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_standards (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    standard_id integer NOT NULL
);


--
-- Name: sample_standards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_standards_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_standards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_standards_id_seq OWNED BY public.sample_standards.id;


--
-- Name: sample_testing_equipment; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sample_testing_equipment (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    equipment_id integer NOT NULL
);


--
-- Name: sample_testing_equipment_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.sample_testing_equipment_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: sample_testing_equipment_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.sample_testing_equipment_id_seq OWNED BY public.sample_testing_equipment.id;


--
-- Name: samples; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.samples (
    id integer NOT NULL,
    sequence_number integer NOT NULL,
    cipher character varying(500) NOT NULL,
    registration_date date NOT NULL,
    client_id integer NOT NULL,
    contract_id integer,
    contract_date date,
    laboratory_id integer NOT NULL,
    accompanying_doc_number character varying(100) NOT NULL,
    accompanying_doc_full_name text NOT NULL,
    accreditation_area_id integer NOT NULL,
    test_code character varying(20) DEFAULT ''::character varying,
    test_type character varying(200) DEFAULT ''::character varying,
    working_days integer NOT NULL,
    sample_received_date date NOT NULL,
    object_info text DEFAULT ''::text,
    object_id character varying(200) DEFAULT ''::character varying,
    cutting_direction character varying(200) DEFAULT ''::character varying,
    test_conditions character varying(100) DEFAULT ''::character varying,
    panel_id character varying(200) DEFAULT ''::character varying,
    material character varying(200) DEFAULT ''::character varying,
    determined_parameters text NOT NULL,
    admin_notes text DEFAULT ''::text,
    deadline date NOT NULL,
    report_type character varying(20) DEFAULT 'PROTOCOL'::character varying NOT NULL,
    pi_number character varying(200) DEFAULT ''::character varying,
    manufacturing_date date,
    uzk_required boolean DEFAULT false,
    further_movement character varying(200) DEFAULT ''::character varying,
    registered_by_id integer NOT NULL,
    replacement_protocol_required boolean DEFAULT false,
    replacement_pi_number character varying(200) DEFAULT ''::character varying,
    test_status character varying(50) DEFAULT ''::character varying,
    report_prepared_by_id integer,
    operator_notes text DEFAULT ''::text,
    protocol_issued_date date,
    protocol_printed_date date,
    replacement_protocol_issued_date date,
    status character varying(20) DEFAULT 'REGISTERED'::character varying NOT NULL,
    files_path character varying(500) DEFAULT ''::character varying,
    created_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone DEFAULT CURRENT_TIMESTAMP,
    verified_by integer,
    verified_at timestamp with time zone,
    protocol_checked_by integer,
    protocol_checked_at timestamp with time zone,
    replacement_count integer DEFAULT 0,
    conditioning_start_datetime timestamp with time zone,
    conditioning_end_datetime timestamp with time zone,
    testing_start_datetime timestamp with time zone,
    testing_end_datetime timestamp with time zone,
    manufacturing_completion_date timestamp with time zone,
    report_prepared_date timestamp with time zone,
    manufacturing boolean DEFAULT false NOT NULL,
    workshop_status character varying(20),
    sample_count integer DEFAULT 1 NOT NULL,
    preparation text DEFAULT ''::text NOT NULL,
    notes text DEFAULT ''::text NOT NULL,
    manufacturing_deadline date,
    additional_sample_count integer DEFAULT 0 NOT NULL,
    workshop_notes text DEFAULT ''::text NOT NULL,
    CONSTRAINT samples_further_movement_check CHECK (((further_movement)::text = ANY ((ARRAY[''::character varying, 'TO_MI'::character varying, 'TO_CHA'::character varying, 'TO_TA'::character varying, 'TO_ACT'::character varying, 'TO_CLIENT_DEPT'::character varying])::text[]))),
    CONSTRAINT samples_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING_VERIFICATION'::character varying, 'REGISTERED'::character varying, 'CANCELLED'::character varying, 'MANUFACTURING'::character varying, 'MANUFACTURED'::character varying, 'TRANSFERRED'::character varying, 'CONDITIONING'::character varying, 'READY_FOR_TEST'::character varying, 'IN_TESTING'::character varying, 'TESTED'::character varying, 'DRAFT_READY'::character varying, 'RESULTS_UPLOADED'::character varying, 'PROTOCOL_ISSUED'::character varying, 'COMPLETED'::character varying, 'REPLACEMENT_PROTOCOL'::character varying])::text[]))),
    CONSTRAINT samples_workshop_status_check CHECK ((((workshop_status)::text = ANY ((ARRAY['IN_WORKSHOP'::character varying, 'COMPLETED'::character varying, 'CANCELLED'::character varying])::text[])) OR (workshop_status IS NULL)))
);


--
-- Name: COLUMN samples.registered_by_id; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.registered_by_id IS '╨Я╨╡╤А╨▓╤Л╨╣ ╨░╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А, ╨║╨╛╤В╨╛╤А╤Л╨╣ ╨╖╨░╤А╨╡╨│╨╕╤Б╤В╤А╨╕╤А╨╛╨▓╨░╨╗ ╨╛╨▒╤А╨░╨╖╨╡╤Ж';


--
-- Name: COLUMN samples.status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.status IS '╨б╤В╨░╤В╤Г╤Б ╨╛╨▒╤А╨░╨╖╤Ж╨░: PENDING_VERIFICATION, REGISTERED, CANCELLED, CONDITIONING, READY_FOR_TEST, IN_TESTING, TESTED, DRAFT_READY, RESULTS_UPLOADED, PROTOCOL_ISSUED, COMPLETED';


--
-- Name: COLUMN samples.verified_by; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.verified_by IS '╨Т╤В╨╛╤А╨╛╨╣ ╨░╨┤╨╝╨╕╨╜╨╕╤Б╤В╤А╨░╤В╨╛╤А, ╨║╨╛╤В╨╛╤А╤Л╨╣ ╨┐╤А╨╛╨▓╨╡╤А╨╕╨╗ ╨╕ ╨┐╨╛╨┤╤В╨▓╨╡╤А╨┤╨╕╨╗ ╤А╨╡╨│╨╕╤Б╤В╤А╨░╤Ж╨╕╤О';


--
-- Name: COLUMN samples.verified_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.verified_at IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨┐╤А╨╛╨▓╨╡╤А╨║╨╕ ╤А╨╡╨│╨╕╤Б╤В╤А╨░╤Ж╨╕╨╕';


--
-- Name: COLUMN samples.protocol_checked_by; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.protocol_checked_by IS '╨б╨╛╤В╤А╤Г╨┤╨╜╨╕╨║ ╨б╨Ь╨Ъ, ╨║╨╛╤В╨╛╤А╤Л╨╣ ╨┐╤А╨╛╨▓╨╡╤А╨╕╨╗ ╨┐╤А╨╛╤В╨╛╨║╨╛╨╗';


--
-- Name: COLUMN samples.protocol_checked_at; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.protocol_checked_at IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨┐╤А╨╛╨▓╨╡╤А╨║╨╕ ╨┐╤А╨╛╤В╨╛╨║╨╛╨╗╨░';


--
-- Name: COLUMN samples.replacement_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.replacement_count IS '╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨▓╤Л╨┐╤Г╤Й╨╡╨╜╨╜╤Л╤Е ╨╖╨░╨╝╨╡╤Й╨░╤О╤Й╨╕╤Е ╨┐╤А╨╛╤В╨╛╨║╨╛╨╗╨╛╨▓';


--
-- Name: COLUMN samples.conditioning_start_datetime; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.conditioning_start_datetime IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨╜╨░╤З╨░╨╗╨░ ╨║╨╛╨╜╨┤╨╕╤Ж╨╕╨╛╨╜╨╕╤А╨╛╨▓╨░╨╜╨╕╤П (╨┤╨╗╤П ╨е╨Р, ╨в╨Р)';


--
-- Name: COLUMN samples.conditioning_end_datetime; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.conditioning_end_datetime IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨╛╨║╨╛╨╜╤З╨░╨╜╨╕╤П ╨║╨╛╨╜╨┤╨╕╤Ж╨╕╨╛╨╜╨╕╤А╨╛╨▓╨░╨╜╨╕╤П (╨┤╨╗╤П ╨е╨Р, ╨в╨Р)';


--
-- Name: COLUMN samples.testing_start_datetime; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.testing_start_datetime IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨╜╨░╤З╨░╨╗╨░ ╨╕╤Б╨┐╤Л╤В╨░╨╜╨╕╤П (╨┤╨╗╤П ╨е╨Р, ╨в╨Р, ╨г╨Ъ╨Ш)';


--
-- Name: COLUMN samples.testing_end_datetime; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.testing_end_datetime IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨╛╨║╨╛╨╜╤З╨░╨╜╨╕╤П ╨╕╤Б╨┐╤Л╤В╨░╨╜╨╕╤П (╨┤╨╗╤П ╨▓╤Б╨╡╤Е ╨╗╨░╨▒╨╛╤А╨░╤В╨╛╤А╨╕╨╣)';


--
-- Name: COLUMN samples.manufacturing_completion_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.manufacturing_completion_date IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨╖╨░╨▓╨╡╤А╤И╨╡╨╜╨╕╤П ╨╕╨╖╨│╨╛╤В╨╛╨▓╨╗╨╡╨╜╨╕╤П (╨╖╨░╨┐╨╛╨╗╨╜╤П╨╡╤В╤Б╤П ╨┐╤А╨╕ ╨╜╨░╨╢╨░╤В╨╕╨╕ ╨║╨╜╨╛╨┐╨║╨╕)';


--
-- Name: COLUMN samples.report_prepared_date; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.report_prepared_date IS '╨Ф╨░╤В╨░ ╨╕ ╨▓╤А╨╡╨╝╤П ╨┐╨╛╨┤╨│╨╛╤В╨╛╨▓╨║╨╕ ╨╛╤В╤З╤С╤В╨░ (╨╕╨╖╨╝╨╡╨╜╨╡╨╜╨╛ ╤Б DATE ╨╜╨░ TIMESTAMP ╨▓ v3.2.4)';


--
-- Name: COLUMN samples.manufacturing; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.manufacturing IS '╨в╤А╨╡╨▒╤Г╨╡╤В╤Б╤П ╨╕╨╖╨│╨╛╤В╨╛╨▓╨╗╨╡╨╜╨╕╨╡ (boolean: true = ╤В╤А╨╡╨▒╤Г╨╡╤В╤Б╤П, false = ╨╜╨╡ ╤В╤А╨╡╨▒╤Г╨╡╤В╤Б╤П)';


--
-- Name: COLUMN samples.workshop_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.workshop_status IS '╨б╤В╨░╤В╤Г╤Б ╨╛╨▒╤А╨░╨╖╤Ж╨░ ╨▓ ╨╝╨░╤Б╤В╨╡╤А╤Б╨║╨╛╨╣: IN_WORKSHOP (╨Т ╨╝╨░╤Б╤В╨╡╤А╤Б╨║╨╛╨╣), COMPLETED (╨У╨╛╤В╨╛╨▓╨╛), NULL (╨╜╨╡ ╤В╤А╨╡╨▒╤Г╨╡╤В ╨╕╨╖╨│╨╛╤В╨╛╨▓╨╗╨╡╨╜╨╕╤П)';


--
-- Name: COLUMN samples.sample_count; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.sample_count IS '╨Ъ╨╛╨╗╨╕╤З╨╡╤Б╤В╨▓╨╛ ╨╛╨▒╤А╨░╨╖╤Ж╨╛╨▓';


--
-- Name: COLUMN samples.manufacturing_deadline; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.samples.manufacturing_deadline IS '╨б╤А╨╛╨║ ╨╕╨╖╨│╨╛╤В╨╛╨▓╨╗╨╡╨╜╨╕╤П (╨┤╨╗╤П ╨╝╨░╤Б╤В╨╡╤А╤Б╨║╨╛╨╣)';


--
-- Name: samples_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.samples_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: samples_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.samples_id_seq OWNED BY public.samples.id;


--
-- Name: standard_accreditation_areas; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.standard_accreditation_areas (
    id integer NOT NULL,
    standard_id integer NOT NULL,
    accreditation_area_id integer NOT NULL
);


--
-- Name: standard_accreditation_areas_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.standard_accreditation_areas_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: standard_accreditation_areas_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.standard_accreditation_areas_id_seq OWNED BY public.standard_accreditation_areas.id;


--
-- Name: standard_laboratories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.standard_laboratories (
    id integer NOT NULL,
    standard_id integer NOT NULL,
    laboratory_id integer NOT NULL
);


--
-- Name: standard_laboratories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.standard_laboratories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: standard_laboratories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.standard_laboratories_id_seq OWNED BY public.standard_laboratories.id;


--
-- Name: standards; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.standards (
    id integer NOT NULL,
    code character varying(50) NOT NULL,
    name character varying(500) NOT NULL,
    is_active boolean DEFAULT true,
    test_code character varying(20) DEFAULT ''::character varying,
    test_type character varying(200) DEFAULT ''::character varying
);


--
-- Name: standards_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.standards_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: standards_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.standards_id_seq OWNED BY public.standards.id;


--
-- Name: time_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.time_log (
    id integer NOT NULL,
    employee_id integer NOT NULL,
    date date NOT NULL,
    start_time time without time zone NOT NULL,
    end_time time without time zone NOT NULL,
    work_type character varying(200) NOT NULL,
    sample_id integer,
    notes text DEFAULT ''::text
);


--
-- Name: time_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.time_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: time_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.time_log_id_seq OWNED BY public.time_log.id;


--
-- Name: user_additional_laboratories; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_additional_laboratories (
    id integer NOT NULL,
    user_id integer NOT NULL,
    laboratory_id integer NOT NULL
);


--
-- Name: user_additional_laboratories_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_additional_laboratories_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_additional_laboratories_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_additional_laboratories_id_seq OWNED BY public.user_additional_laboratories.id;


--
-- Name: user_permissions_override; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.user_permissions_override (
    id integer NOT NULL,
    user_id integer NOT NULL,
    journal_id integer NOT NULL,
    column_id integer,
    access_level character varying(10) DEFAULT 'NONE'::character varying NOT NULL,
    reason text NOT NULL,
    granted_by_id integer NOT NULL,
    granted_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    valid_until date,
    is_active boolean DEFAULT true
);


--
-- Name: user_permissions_override_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.user_permissions_override_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: user_permissions_override_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.user_permissions_override_id_seq OWNED BY public.user_permissions_override.id;


--
-- Name: users; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.users (
    id integer NOT NULL,
    username character varying(100) NOT NULL,
    password_hash character varying(255) NOT NULL,
    email character varying(255) DEFAULT ''::character varying,
    first_name character varying(100) DEFAULT ''::character varying,
    last_name character varying(100) DEFAULT ''::character varying,
    role character varying(20) DEFAULT 'OTHER'::character varying NOT NULL,
    laboratory_id integer,
    is_active boolean DEFAULT true,
    is_staff boolean DEFAULT false,
    is_superuser boolean DEFAULT false,
    ui_preferences jsonb DEFAULT '{}'::jsonb,
    last_login timestamp without time zone,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    is_trainee boolean DEFAULT false NOT NULL,
    mentor_id integer,
    CONSTRAINT chk_mentor_not_self CHECK (((mentor_id IS NULL) OR (mentor_id <> id)))
);


--
-- Name: COLUMN users.role; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.users.role IS '╨а╨╛╨╗╤М ╨┐╨╛╨╗╤М╨╖╨╛╨▓╨░╤В╨╡╨╗╤П: CEO, CTO, SYSADMIN, LAB_HEAD, TESTER, CLIENT_DEPT_HEAD, CLIENT_MANAGER, CONTRACT_SPEC, QMS_HEAD, QMS_ADMIN, METROLOGIST, WORKSHOP, ACCOUNTANT, OTHER';


--
-- Name: users_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.users_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: users_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.users_id_seq OWNED BY public.users.id;


--
-- Name: weight_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.weight_log (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    measured_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    weight numeric(10,4) NOT NULL,
    test_type character varying(50) NOT NULL,
    measured_by_id integer NOT NULL,
    equipment_id integer NOT NULL,
    notes text DEFAULT ''::text
);


--
-- Name: weight_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.weight_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: weight_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.weight_log_id_seq OWNED BY public.weight_log.id;


--
-- Name: workshop_log; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.workshop_log (
    id integer NOT NULL,
    sample_id integer NOT NULL,
    operator_id integer NOT NULL,
    operation_date date NOT NULL,
    operation_type character varying(200) NOT NULL,
    equipment_id integer NOT NULL,
    cutting_params text DEFAULT ''::text,
    quantity integer DEFAULT 1,
    quality_check boolean DEFAULT true,
    notes text DEFAULT ''::text,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP
);


--
-- Name: workshop_log_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

CREATE SEQUENCE public.workshop_log_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;


--
-- Name: workshop_log_id_seq; Type: SEQUENCE OWNED BY; Schema: public; Owner: -
--

ALTER SEQUENCE public.workshop_log_id_seq OWNED BY public.workshop_log.id;


--
-- Name: accreditation_areas id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accreditation_areas ALTER COLUMN id SET DEFAULT nextval('public.accreditation_areas_id_seq'::regclass);


--
-- Name: client_contacts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_contacts ALTER COLUMN id SET DEFAULT nextval('public.client_contacts_id_seq'::regclass);


--
-- Name: clients id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients ALTER COLUMN id SET DEFAULT nextval('public.clients_id_seq'::regclass);


--
-- Name: climate_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.climate_log ALTER COLUMN id SET DEFAULT nextval('public.climate_log_id_seq'::regclass);


--
-- Name: contracts id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts ALTER COLUMN id SET DEFAULT nextval('public.contracts_id_seq'::regclass);


--
-- Name: equipment id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment ALTER COLUMN id SET DEFAULT nextval('public.equipment_id_seq'::regclass);


--
-- Name: equipment_accreditation_areas id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_accreditation_areas ALTER COLUMN id SET DEFAULT nextval('public.equipment_accreditation_areas_id_seq'::regclass);


--
-- Name: equipment_maintenance id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_maintenance ALTER COLUMN id SET DEFAULT nextval('public.equipment_maintenance_id_seq'::regclass);


--
-- Name: holidays id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holidays ALTER COLUMN id SET DEFAULT nextval('public.holidays_id_seq'::regclass);


--
-- Name: journal_columns id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_columns ALTER COLUMN id SET DEFAULT nextval('public.journal_columns_id_seq'::regclass);


--
-- Name: journals id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journals ALTER COLUMN id SET DEFAULT nextval('public.journals_id_seq'::regclass);


--
-- Name: laboratories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratories ALTER COLUMN id SET DEFAULT nextval('public.laboratories_id_seq'::regclass);


--
-- Name: permissions_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_log ALTER COLUMN id SET DEFAULT nextval('public.permissions_log_id_seq'::regclass);


--
-- Name: role_permissions id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions ALTER COLUMN id SET DEFAULT nextval('public.role_permissions_id_seq'::regclass);


--
-- Name: sample_auxiliary_equipment id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_auxiliary_equipment ALTER COLUMN id SET DEFAULT nextval('public.sample_auxiliary_equipment_id_seq'::regclass);


--
-- Name: sample_manufacturing_auxiliary_equipment id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_auxiliary_equipment ALTER COLUMN id SET DEFAULT nextval('public.sample_manufacturing_auxiliary_equipment_id_seq'::regclass);


--
-- Name: sample_manufacturing_measuring_instruments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_measuring_instruments ALTER COLUMN id SET DEFAULT nextval('public.sample_manufacturing_measuring_instruments_id_seq'::regclass);


--
-- Name: sample_manufacturing_operators id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_operators ALTER COLUMN id SET DEFAULT nextval('public.sample_manufacturing_operators_id_seq'::regclass);


--
-- Name: sample_manufacturing_testing_equipment id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_testing_equipment ALTER COLUMN id SET DEFAULT nextval('public.sample_manufacturing_testing_equipment_id_seq'::regclass);


--
-- Name: sample_measuring_instruments id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_measuring_instruments ALTER COLUMN id SET DEFAULT nextval('public.sample_measuring_instruments_id_seq'::regclass);


--
-- Name: sample_operators id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_operators ALTER COLUMN id SET DEFAULT nextval('public.sample_operators_id_seq'::regclass);


--
-- Name: sample_standards id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_standards ALTER COLUMN id SET DEFAULT nextval('public.sample_standards_id_seq'::regclass);


--
-- Name: sample_testing_equipment id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_testing_equipment ALTER COLUMN id SET DEFAULT nextval('public.sample_testing_equipment_id_seq'::regclass);


--
-- Name: samples id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples ALTER COLUMN id SET DEFAULT nextval('public.samples_id_seq'::regclass);


--
-- Name: standard_accreditation_areas id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_accreditation_areas ALTER COLUMN id SET DEFAULT nextval('public.standard_accreditation_areas_id_seq'::regclass);


--
-- Name: standard_laboratories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_laboratories ALTER COLUMN id SET DEFAULT nextval('public.standard_laboratories_id_seq'::regclass);


--
-- Name: standards id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standards ALTER COLUMN id SET DEFAULT nextval('public.standards_id_seq'::regclass);


--
-- Name: time_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_log ALTER COLUMN id SET DEFAULT nextval('public.time_log_id_seq'::regclass);


--
-- Name: user_additional_laboratories id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_additional_laboratories ALTER COLUMN id SET DEFAULT nextval('public.user_additional_laboratories_id_seq'::regclass);


--
-- Name: user_permissions_override id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permissions_override ALTER COLUMN id SET DEFAULT nextval('public.user_permissions_override_id_seq'::regclass);


--
-- Name: users id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users ALTER COLUMN id SET DEFAULT nextval('public.users_id_seq'::regclass);


--
-- Name: weight_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weight_log ALTER COLUMN id SET DEFAULT nextval('public.weight_log_id_seq'::regclass);


--
-- Name: workshop_log id; Type: DEFAULT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workshop_log ALTER COLUMN id SET DEFAULT nextval('public.workshop_log_id_seq'::regclass);


--
-- Name: accreditation_areas accreditation_areas_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accreditation_areas
    ADD CONSTRAINT accreditation_areas_code_key UNIQUE (code);


--
-- Name: accreditation_areas accreditation_areas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.accreditation_areas
    ADD CONSTRAINT accreditation_areas_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_name_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_name_key UNIQUE (name);


--
-- Name: auth_group_permissions auth_group_permissions_group_id_permission_id_0cd325b0_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_permission_id_0cd325b0_uniq UNIQUE (group_id, permission_id);


--
-- Name: auth_group_permissions auth_group_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_pkey PRIMARY KEY (id);


--
-- Name: auth_group auth_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group
    ADD CONSTRAINT auth_group_pkey PRIMARY KEY (id);


--
-- Name: auth_permission auth_permission_content_type_id_codename_01ab375a_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_codename_01ab375a_uniq UNIQUE (content_type_id, codename);


--
-- Name: auth_permission auth_permission_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_pkey PRIMARY KEY (id);


--
-- Name: client_contacts client_contacts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_contacts
    ADD CONSTRAINT client_contacts_pkey PRIMARY KEY (id);


--
-- Name: clients clients_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.clients
    ADD CONSTRAINT clients_pkey PRIMARY KEY (id);


--
-- Name: climate_log climate_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.climate_log
    ADD CONSTRAINT climate_log_pkey PRIMARY KEY (id);


--
-- Name: contracts contracts_client_id_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT contracts_client_id_number_key UNIQUE (client_id, number);


--
-- Name: contracts contracts_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT contracts_pkey PRIMARY KEY (id);


--
-- Name: django_admin_log django_admin_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_pkey PRIMARY KEY (id);


--
-- Name: django_content_type django_content_type_app_label_model_76bd3d3b_uniq; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_app_label_model_76bd3d3b_uniq UNIQUE (app_label, model);


--
-- Name: django_content_type django_content_type_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_content_type
    ADD CONSTRAINT django_content_type_pkey PRIMARY KEY (id);


--
-- Name: django_migrations django_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_migrations
    ADD CONSTRAINT django_migrations_pkey PRIMARY KEY (id);


--
-- Name: django_session django_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_session
    ADD CONSTRAINT django_session_pkey PRIMARY KEY (session_key);


--
-- Name: equipment equipment_accounting_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_accounting_number_key UNIQUE (accounting_number);


--
-- Name: equipment_accreditation_areas equipment_accreditation_areas_equipment_id_accreditation_ar_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_accreditation_areas
    ADD CONSTRAINT equipment_accreditation_areas_equipment_id_accreditation_ar_key UNIQUE (equipment_id, accreditation_area_id);


--
-- Name: equipment_accreditation_areas equipment_accreditation_areas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_accreditation_areas
    ADD CONSTRAINT equipment_accreditation_areas_pkey PRIMARY KEY (id);


--
-- Name: equipment equipment_inventory_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_inventory_number_key UNIQUE (inventory_number);


--
-- Name: equipment_maintenance equipment_maintenance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_maintenance
    ADD CONSTRAINT equipment_maintenance_pkey PRIMARY KEY (id);


--
-- Name: equipment equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_pkey PRIMARY KEY (id);


--
-- Name: holidays holidays_date_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT holidays_date_key UNIQUE (date);


--
-- Name: holidays holidays_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.holidays
    ADD CONSTRAINT holidays_pkey PRIMARY KEY (id);


--
-- Name: journal_columns journal_columns_journal_id_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_columns
    ADD CONSTRAINT journal_columns_journal_id_code_key UNIQUE (journal_id, code);


--
-- Name: journal_columns journal_columns_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_columns
    ADD CONSTRAINT journal_columns_pkey PRIMARY KEY (id);


--
-- Name: journals journals_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journals
    ADD CONSTRAINT journals_code_key UNIQUE (code);


--
-- Name: journals journals_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journals
    ADD CONSTRAINT journals_pkey PRIMARY KEY (id);


--
-- Name: laboratories laboratories_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_code_key UNIQUE (code);


--
-- Name: laboratories laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_pkey PRIMARY KEY (id);


--
-- Name: permissions_log permissions_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_log
    ADD CONSTRAINT permissions_log_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_pkey PRIMARY KEY (id);


--
-- Name: role_permissions role_permissions_role_journal_id_column_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_role_journal_id_column_id_key UNIQUE (role, journal_id, column_id);


--
-- Name: sample_auxiliary_equipment sample_auxiliary_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_auxiliary_equipment
    ADD CONSTRAINT sample_auxiliary_equipment_pkey PRIMARY KEY (id);


--
-- Name: sample_auxiliary_equipment sample_auxiliary_equipment_sample_id_equipment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_auxiliary_equipment
    ADD CONSTRAINT sample_auxiliary_equipment_sample_id_equipment_id_key UNIQUE (sample_id, equipment_id);


--
-- Name: sample_files sample_files_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_files
    ADD CONSTRAINT sample_files_pkey PRIMARY KEY (id);


--
-- Name: sample_manufacturing_auxiliary_equipment sample_manufacturing_auxiliary_equip_sample_id_equipment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_auxiliary_equipment
    ADD CONSTRAINT sample_manufacturing_auxiliary_equip_sample_id_equipment_id_key UNIQUE (sample_id, equipment_id);


--
-- Name: sample_manufacturing_auxiliary_equipment sample_manufacturing_auxiliary_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_auxiliary_equipment
    ADD CONSTRAINT sample_manufacturing_auxiliary_equipment_pkey PRIMARY KEY (id);


--
-- Name: sample_manufacturing_measuring_instruments sample_manufacturing_measuring_instr_sample_id_equipment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_measuring_instruments
    ADD CONSTRAINT sample_manufacturing_measuring_instr_sample_id_equipment_id_key UNIQUE (sample_id, equipment_id);


--
-- Name: sample_manufacturing_measuring_instruments sample_manufacturing_measuring_instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_measuring_instruments
    ADD CONSTRAINT sample_manufacturing_measuring_instruments_pkey PRIMARY KEY (id);


--
-- Name: sample_manufacturing_operators sample_manufacturing_operators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_operators
    ADD CONSTRAINT sample_manufacturing_operators_pkey PRIMARY KEY (id);


--
-- Name: sample_manufacturing_operators sample_manufacturing_operators_sample_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_operators
    ADD CONSTRAINT sample_manufacturing_operators_sample_id_user_id_key UNIQUE (sample_id, user_id);


--
-- Name: sample_manufacturing_testing_equipment sample_manufacturing_testing_equipme_sample_id_equipment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_testing_equipment
    ADD CONSTRAINT sample_manufacturing_testing_equipme_sample_id_equipment_id_key UNIQUE (sample_id, equipment_id);


--
-- Name: sample_manufacturing_testing_equipment sample_manufacturing_testing_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_testing_equipment
    ADD CONSTRAINT sample_manufacturing_testing_equipment_pkey PRIMARY KEY (id);


--
-- Name: sample_measuring_instruments sample_measuring_instruments_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_measuring_instruments
    ADD CONSTRAINT sample_measuring_instruments_pkey PRIMARY KEY (id);


--
-- Name: sample_measuring_instruments sample_measuring_instruments_sample_id_equipment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_measuring_instruments
    ADD CONSTRAINT sample_measuring_instruments_sample_id_equipment_id_key UNIQUE (sample_id, equipment_id);


--
-- Name: sample_operators sample_operators_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_operators
    ADD CONSTRAINT sample_operators_pkey PRIMARY KEY (id);


--
-- Name: sample_operators sample_operators_sample_id_user_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_operators
    ADD CONSTRAINT sample_operators_sample_id_user_id_key UNIQUE (sample_id, user_id);


--
-- Name: sample_standards sample_standards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_standards
    ADD CONSTRAINT sample_standards_pkey PRIMARY KEY (id);


--
-- Name: sample_standards sample_standards_sample_id_standard_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_standards
    ADD CONSTRAINT sample_standards_sample_id_standard_id_key UNIQUE (sample_id, standard_id);


--
-- Name: sample_testing_equipment sample_testing_equipment_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_testing_equipment
    ADD CONSTRAINT sample_testing_equipment_pkey PRIMARY KEY (id);


--
-- Name: sample_testing_equipment sample_testing_equipment_sample_id_equipment_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_testing_equipment
    ADD CONSTRAINT sample_testing_equipment_sample_id_equipment_id_key UNIQUE (sample_id, equipment_id);


--
-- Name: samples samples_cipher_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_cipher_key UNIQUE (cipher);


--
-- Name: samples samples_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_pkey PRIMARY KEY (id);


--
-- Name: samples samples_sequence_number_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_sequence_number_key UNIQUE (sequence_number);


--
-- Name: standard_accreditation_areas standard_accreditation_areas_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_accreditation_areas
    ADD CONSTRAINT standard_accreditation_areas_pkey PRIMARY KEY (id);


--
-- Name: standard_accreditation_areas standard_accreditation_areas_standard_id_accreditation_area_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_accreditation_areas
    ADD CONSTRAINT standard_accreditation_areas_standard_id_accreditation_area_key UNIQUE (standard_id, accreditation_area_id);


--
-- Name: standard_laboratories standard_laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_laboratories
    ADD CONSTRAINT standard_laboratories_pkey PRIMARY KEY (id);


--
-- Name: standard_laboratories standard_laboratories_standard_id_laboratory_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_laboratories
    ADD CONSTRAINT standard_laboratories_standard_id_laboratory_id_key UNIQUE (standard_id, laboratory_id);


--
-- Name: standards standards_code_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standards
    ADD CONSTRAINT standards_code_key UNIQUE (code);


--
-- Name: standards standards_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standards
    ADD CONSTRAINT standards_pkey PRIMARY KEY (id);


--
-- Name: time_log time_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_log
    ADD CONSTRAINT time_log_pkey PRIMARY KEY (id);


--
-- Name: user_additional_laboratories uq_user_additional_lab; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_additional_laboratories
    ADD CONSTRAINT uq_user_additional_lab UNIQUE (user_id, laboratory_id);


--
-- Name: user_additional_laboratories user_additional_laboratories_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_additional_laboratories
    ADD CONSTRAINT user_additional_laboratories_pkey PRIMARY KEY (id);


--
-- Name: user_permissions_override user_permissions_override_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permissions_override
    ADD CONSTRAINT user_permissions_override_pkey PRIMARY KEY (id);


--
-- Name: user_permissions_override user_permissions_override_user_id_journal_id_column_id_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permissions_override
    ADD CONSTRAINT user_permissions_override_user_id_journal_id_column_id_key UNIQUE (user_id, journal_id, column_id);


--
-- Name: users users_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);


--
-- Name: users users_username_key; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_username_key UNIQUE (username);


--
-- Name: weight_log weight_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weight_log
    ADD CONSTRAINT weight_log_pkey PRIMARY KEY (id);


--
-- Name: workshop_log workshop_log_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workshop_log
    ADD CONSTRAINT workshop_log_pkey PRIMARY KEY (id);


--
-- Name: auth_group_name_a6ea08ec_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_name_a6ea08ec_like ON public.auth_group USING btree (name varchar_pattern_ops);


--
-- Name: auth_group_permissions_group_id_b120cbf9; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_group_id_b120cbf9 ON public.auth_group_permissions USING btree (group_id);


--
-- Name: auth_group_permissions_permission_id_84c5c92e; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_group_permissions_permission_id_84c5c92e ON public.auth_group_permissions USING btree (permission_id);


--
-- Name: auth_permission_content_type_id_2f476e4b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX auth_permission_content_type_id_2f476e4b ON public.auth_permission USING btree (content_type_id);


--
-- Name: django_admin_log_content_type_id_c4bce8eb; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_content_type_id_c4bce8eb ON public.django_admin_log USING btree (content_type_id);


--
-- Name: django_admin_log_user_id_c564eba6; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_admin_log_user_id_c564eba6 ON public.django_admin_log USING btree (user_id);


--
-- Name: django_session_expire_date_a5c62663; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_expire_date_a5c62663 ON public.django_session USING btree (expire_date);


--
-- Name: django_session_session_key_c0390e0f_like; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX django_session_session_key_c0390e0f_like ON public.django_session USING btree (session_key varchar_pattern_ops);


--
-- Name: idx_climate_log_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_climate_log_date ON public.climate_log USING btree (measured_at);


--
-- Name: idx_climate_log_laboratory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_climate_log_laboratory ON public.climate_log USING btree (laboratory_id);


--
-- Name: idx_contracts_client; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contracts_client ON public.contracts USING btree (client_id);


--
-- Name: idx_contracts_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_contracts_status ON public.contracts USING btree (status);


--
-- Name: idx_equipment_laboratory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_equipment_laboratory ON public.equipment USING btree (laboratory_id);


--
-- Name: idx_equipment_maintenance_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_equipment_maintenance_date ON public.equipment_maintenance USING btree (maintenance_date);


--
-- Name: idx_equipment_maintenance_equipment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_equipment_maintenance_equipment ON public.equipment_maintenance USING btree (equipment_id);


--
-- Name: idx_equipment_maintenance_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_equipment_maintenance_type ON public.equipment_maintenance USING btree (maintenance_type);


--
-- Name: idx_equipment_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_equipment_status ON public.equipment USING btree (status);


--
-- Name: idx_equipment_type; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_equipment_type ON public.equipment USING btree (equipment_type);


--
-- Name: idx_role_permissions_role; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_role_permissions_role ON public.role_permissions USING btree (role);


--
-- Name: idx_sae_equipment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sae_equipment ON public.sample_auxiliary_equipment USING btree (equipment_id);


--
-- Name: idx_sae_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sae_sample ON public.sample_auxiliary_equipment USING btree (sample_id);


--
-- Name: idx_sample_manufacturing_mi_equipment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_manufacturing_mi_equipment ON public.sample_manufacturing_measuring_instruments USING btree (equipment_id);


--
-- Name: idx_sample_manufacturing_mi_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_manufacturing_mi_sample ON public.sample_manufacturing_measuring_instruments USING btree (sample_id);


--
-- Name: idx_sample_manufacturing_op_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_manufacturing_op_sample ON public.sample_manufacturing_operators USING btree (sample_id);


--
-- Name: idx_sample_manufacturing_op_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_manufacturing_op_user ON public.sample_manufacturing_operators USING btree (user_id);


--
-- Name: idx_sample_manufacturing_te_equipment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_manufacturing_te_equipment ON public.sample_manufacturing_testing_equipment USING btree (equipment_id);


--
-- Name: idx_sample_manufacturing_te_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_manufacturing_te_sample ON public.sample_manufacturing_testing_equipment USING btree (sample_id);


--
-- Name: idx_sample_standards_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_standards_sample ON public.sample_standards USING btree (sample_id);


--
-- Name: idx_sample_standards_standard; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_sample_standards_standard ON public.sample_standards USING btree (standard_id);


--
-- Name: idx_samples_cipher; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_cipher ON public.samples USING btree (cipher);


--
-- Name: idx_samples_client; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_client ON public.samples USING btree (client_id);


--
-- Name: idx_samples_conditioning_start_datetime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_conditioning_start_datetime ON public.samples USING btree (conditioning_start_datetime);


--
-- Name: idx_samples_deadline; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_deadline ON public.samples USING btree (deadline);


--
-- Name: idx_samples_laboratory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_laboratory ON public.samples USING btree (laboratory_id);


--
-- Name: idx_samples_manufacturing; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_manufacturing ON public.samples USING btree (manufacturing) WHERE (manufacturing = true);


--
-- Name: INDEX idx_samples_manufacturing; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.idx_samples_manufacturing IS '╨Ш╨╜╨┤╨╡╨║╤Б ╨┤╨╗╤П ╨╢╤Г╤А╨╜╨░╨╗╨░ ╨╝╨░╤Б╤В╨╡╤А╤Б╨║╨╛╨╣';


--
-- Name: idx_samples_manufacturing_completion_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_manufacturing_completion_date ON public.samples USING btree (manufacturing_completion_date) WHERE (manufacturing_completion_date IS NOT NULL);


--
-- Name: idx_samples_protocol_checked_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_protocol_checked_by ON public.samples USING btree (protocol_checked_by);


--
-- Name: idx_samples_qms_check; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_qms_check ON public.samples USING btree (status) WHERE ((status)::text = ANY ((ARRAY['DRAFT_READY'::character varying, 'RESULTS_UPLOADED'::character varying])::text[]));


--
-- Name: idx_samples_registered_by_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_registered_by_id ON public.samples USING btree (registered_by_id);


--
-- Name: idx_samples_registration_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_registration_date ON public.samples USING btree (registration_date);


--
-- Name: idx_samples_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_status ON public.samples USING btree (status);


--
-- Name: idx_samples_testing_end_datetime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_testing_end_datetime ON public.samples USING btree (testing_end_datetime);


--
-- Name: idx_samples_verified_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_verified_by ON public.samples USING btree (verified_by);


--
-- Name: idx_samples_workshop_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_samples_workshop_status ON public.samples USING btree (workshop_status) WHERE (workshop_status IS NOT NULL);


--
-- Name: INDEX idx_samples_workshop_status; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON INDEX public.idx_samples_workshop_status IS '╨Ш╨╜╨┤╨╡╨║╤Б ╨┤╨╗╤П ╨▒╤Л╤Б╤В╤А╨╛╨╣ ╤Д╨╕╨╗╤М╤В╤А╨░╤Ж╨╕╨╕ ╨╛╨▒╤А╨░╨╖╤Ж╨╛╨▓ ╨╝╨░╤Б╤В╨╡╤А╤Б╨║╨╛╨╣ ╨▓ ╨╢╤Г╤А╨╜╨░╨╗╨╡';


--
-- Name: idx_smae_equipment; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_smae_equipment ON public.sample_manufacturing_auxiliary_equipment USING btree (equipment_id);


--
-- Name: idx_smae_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_smae_sample ON public.sample_manufacturing_auxiliary_equipment USING btree (sample_id);


--
-- Name: idx_standard_laboratories_laboratory; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_standard_laboratories_laboratory ON public.standard_laboratories USING btree (laboratory_id);


--
-- Name: idx_standard_laboratories_standard; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_standard_laboratories_standard ON public.standard_laboratories USING btree (standard_id);


--
-- Name: idx_ual_laboratory_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ual_laboratory_id ON public.user_additional_laboratories USING btree (laboratory_id);


--
-- Name: idx_ual_user_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_ual_user_id ON public.user_additional_laboratories USING btree (user_id);


--
-- Name: idx_user_permissions_user; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_user_permissions_user ON public.user_permissions_override USING btree (user_id);


--
-- Name: idx_users_is_trainee; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_is_trainee ON public.users USING btree (is_trainee) WHERE (is_trainee = true);


--
-- Name: idx_users_mentor_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_users_mentor_id ON public.users USING btree (mentor_id) WHERE (mentor_id IS NOT NULL);


--
-- Name: idx_weight_log_date; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_weight_log_date ON public.weight_log USING btree (measured_at);


--
-- Name: idx_weight_log_sample; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX idx_weight_log_sample ON public.weight_log USING btree (sample_id);


--
-- Name: sample_files_sample_id_febfde6b; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sample_files_sample_id_febfde6b ON public.sample_files USING btree (sample_id);


--
-- Name: sample_files_uploaded_by_id_156ebc7c; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX sample_files_uploaded_by_id_156ebc7c ON public.sample_files USING btree (uploaded_by_id);


--
-- Name: users block_user_delete; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER block_user_delete BEFORE DELETE ON public.users FOR EACH ROW EXECUTE FUNCTION public.prevent_user_deletion();


--
-- Name: auth_group_permissions auth_group_permissio_permission_id_84c5c92e_fk_auth_perm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissio_permission_id_84c5c92e_fk_auth_perm FOREIGN KEY (permission_id) REFERENCES public.auth_permission(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_group_permissions auth_group_permissions_group_id_b120cbf9_fk_auth_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_group_permissions
    ADD CONSTRAINT auth_group_permissions_group_id_b120cbf9_fk_auth_group_id FOREIGN KEY (group_id) REFERENCES public.auth_group(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: auth_permission auth_permission_content_type_id_2f476e4b_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.auth_permission
    ADD CONSTRAINT auth_permission_content_type_id_2f476e4b_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: client_contacts client_contacts_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.client_contacts
    ADD CONSTRAINT client_contacts_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;


--
-- Name: climate_log climate_log_laboratory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.climate_log
    ADD CONSTRAINT climate_log_laboratory_id_fkey FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE RESTRICT;


--
-- Name: climate_log climate_log_measured_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.climate_log
    ADD CONSTRAINT climate_log_measured_by_id_fkey FOREIGN KEY (measured_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: contracts contracts_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.contracts
    ADD CONSTRAINT contracts_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE CASCADE;


--
-- Name: django_admin_log django_admin_log_content_type_id_c4bce8eb_fk_django_co; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_content_type_id_c4bce8eb_fk_django_co FOREIGN KEY (content_type_id) REFERENCES public.django_content_type(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: django_admin_log django_admin_log_user_id_c564eba6_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.django_admin_log
    ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_users_id FOREIGN KEY (user_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: equipment_accreditation_areas equipment_accreditation_areas_accreditation_area_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_accreditation_areas
    ADD CONSTRAINT equipment_accreditation_areas_accreditation_area_id_fkey FOREIGN KEY (accreditation_area_id) REFERENCES public.accreditation_areas(id) ON DELETE CASCADE;


--
-- Name: equipment_accreditation_areas equipment_accreditation_areas_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_accreditation_areas
    ADD CONSTRAINT equipment_accreditation_areas_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE CASCADE;


--
-- Name: equipment equipment_laboratory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_laboratory_id_fkey FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE RESTRICT;


--
-- Name: equipment_maintenance equipment_maintenance_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_maintenance
    ADD CONSTRAINT equipment_maintenance_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE CASCADE;


--
-- Name: equipment_maintenance equipment_maintenance_performed_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment_maintenance
    ADD CONSTRAINT equipment_maintenance_performed_by_id_fkey FOREIGN KEY (performed_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: equipment equipment_responsible_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_responsible_person_id_fkey FOREIGN KEY (responsible_person_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: equipment equipment_substitute_person_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.equipment
    ADD CONSTRAINT equipment_substitute_person_id_fkey FOREIGN KEY (substitute_person_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: user_additional_laboratories fk_ual_laboratory; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_additional_laboratories
    ADD CONSTRAINT fk_ual_laboratory FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE CASCADE;


--
-- Name: user_additional_laboratories fk_ual_user; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_additional_laboratories
    ADD CONSTRAINT fk_ual_user FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: users fk_users_mentor; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT fk_users_mentor FOREIGN KEY (mentor_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: journal_columns journal_columns_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.journal_columns
    ADD CONSTRAINT journal_columns_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.journals(id) ON DELETE CASCADE;


--
-- Name: laboratories laboratories_head_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.laboratories
    ADD CONSTRAINT laboratories_head_id_fkey FOREIGN KEY (head_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: permissions_log permissions_log_changed_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_log
    ADD CONSTRAINT permissions_log_changed_by_id_fkey FOREIGN KEY (changed_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: permissions_log permissions_log_column_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_log
    ADD CONSTRAINT permissions_log_column_id_fkey FOREIGN KEY (column_id) REFERENCES public.journal_columns(id) ON DELETE CASCADE;


--
-- Name: permissions_log permissions_log_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_log
    ADD CONSTRAINT permissions_log_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.journals(id) ON DELETE CASCADE;


--
-- Name: permissions_log permissions_log_target_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.permissions_log
    ADD CONSTRAINT permissions_log_target_user_id_fkey FOREIGN KEY (target_user_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: role_permissions role_permissions_column_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_column_id_fkey FOREIGN KEY (column_id) REFERENCES public.journal_columns(id) ON DELETE CASCADE;


--
-- Name: role_permissions role_permissions_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.role_permissions
    ADD CONSTRAINT role_permissions_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.journals(id) ON DELETE CASCADE;


--
-- Name: sample_auxiliary_equipment sample_auxiliary_equipment_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_auxiliary_equipment
    ADD CONSTRAINT sample_auxiliary_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: sample_auxiliary_equipment sample_auxiliary_equipment_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_auxiliary_equipment
    ADD CONSTRAINT sample_auxiliary_equipment_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_files sample_files_sample_id_febfde6b_fk_samples_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_files
    ADD CONSTRAINT sample_files_sample_id_febfde6b_fk_samples_id FOREIGN KEY (sample_id) REFERENCES public.samples(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sample_files sample_files_uploaded_by_id_156ebc7c_fk_users_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_files
    ADD CONSTRAINT sample_files_uploaded_by_id_156ebc7c_fk_users_id FOREIGN KEY (uploaded_by_id) REFERENCES public.users(id) DEFERRABLE INITIALLY DEFERRED;


--
-- Name: sample_manufacturing_auxiliary_equipment sample_manufacturing_auxiliary_equipment_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_auxiliary_equipment
    ADD CONSTRAINT sample_manufacturing_auxiliary_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: sample_manufacturing_auxiliary_equipment sample_manufacturing_auxiliary_equipment_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_auxiliary_equipment
    ADD CONSTRAINT sample_manufacturing_auxiliary_equipment_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_manufacturing_measuring_instruments sample_manufacturing_measuring_instruments_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_measuring_instruments
    ADD CONSTRAINT sample_manufacturing_measuring_instruments_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: sample_manufacturing_measuring_instruments sample_manufacturing_measuring_instruments_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_measuring_instruments
    ADD CONSTRAINT sample_manufacturing_measuring_instruments_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_manufacturing_operators sample_manufacturing_operators_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_operators
    ADD CONSTRAINT sample_manufacturing_operators_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_manufacturing_operators sample_manufacturing_operators_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_operators
    ADD CONSTRAINT sample_manufacturing_operators_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: sample_manufacturing_testing_equipment sample_manufacturing_testing_equipment_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_testing_equipment
    ADD CONSTRAINT sample_manufacturing_testing_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: sample_manufacturing_testing_equipment sample_manufacturing_testing_equipment_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_manufacturing_testing_equipment
    ADD CONSTRAINT sample_manufacturing_testing_equipment_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_measuring_instruments sample_measuring_instruments_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_measuring_instruments
    ADD CONSTRAINT sample_measuring_instruments_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: sample_measuring_instruments sample_measuring_instruments_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_measuring_instruments
    ADD CONSTRAINT sample_measuring_instruments_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_operators sample_operators_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_operators
    ADD CONSTRAINT sample_operators_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_operators sample_operators_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_operators
    ADD CONSTRAINT sample_operators_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: sample_standards sample_standards_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_standards
    ADD CONSTRAINT sample_standards_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: sample_standards sample_standards_standard_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_standards
    ADD CONSTRAINT sample_standards_standard_id_fkey FOREIGN KEY (standard_id) REFERENCES public.standards(id) ON DELETE RESTRICT;


--
-- Name: sample_testing_equipment sample_testing_equipment_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_testing_equipment
    ADD CONSTRAINT sample_testing_equipment_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: sample_testing_equipment sample_testing_equipment_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sample_testing_equipment
    ADD CONSTRAINT sample_testing_equipment_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: samples samples_accreditation_area_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_accreditation_area_id_fkey FOREIGN KEY (accreditation_area_id) REFERENCES public.accreditation_areas(id) ON DELETE RESTRICT;


--
-- Name: samples samples_client_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_client_id_fkey FOREIGN KEY (client_id) REFERENCES public.clients(id) ON DELETE RESTRICT;


--
-- Name: samples samples_contract_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_contract_id_fkey FOREIGN KEY (contract_id) REFERENCES public.contracts(id) ON DELETE RESTRICT;


--
-- Name: samples samples_laboratory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_laboratory_id_fkey FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE RESTRICT;


--
-- Name: samples samples_protocol_checked_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_protocol_checked_by_fkey FOREIGN KEY (protocol_checked_by) REFERENCES public.users(id);


--
-- Name: samples samples_registered_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_registered_by_id_fkey FOREIGN KEY (registered_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: samples samples_report_prepared_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_report_prepared_by_id_fkey FOREIGN KEY (report_prepared_by_id) REFERENCES public.users(id) ON DELETE SET NULL;


--
-- Name: samples samples_verified_by_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.samples
    ADD CONSTRAINT samples_verified_by_fkey FOREIGN KEY (verified_by) REFERENCES public.users(id);


--
-- Name: standard_accreditation_areas standard_accreditation_areas_accreditation_area_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_accreditation_areas
    ADD CONSTRAINT standard_accreditation_areas_accreditation_area_id_fkey FOREIGN KEY (accreditation_area_id) REFERENCES public.accreditation_areas(id) ON DELETE CASCADE;


--
-- Name: standard_accreditation_areas standard_accreditation_areas_standard_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_accreditation_areas
    ADD CONSTRAINT standard_accreditation_areas_standard_id_fkey FOREIGN KEY (standard_id) REFERENCES public.standards(id) ON DELETE CASCADE;


--
-- Name: standard_laboratories standard_laboratories_laboratory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_laboratories
    ADD CONSTRAINT standard_laboratories_laboratory_id_fkey FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE CASCADE;


--
-- Name: standard_laboratories standard_laboratories_standard_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.standard_laboratories
    ADD CONSTRAINT standard_laboratories_standard_id_fkey FOREIGN KEY (standard_id) REFERENCES public.standards(id) ON DELETE CASCADE;


--
-- Name: time_log time_log_employee_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_log
    ADD CONSTRAINT time_log_employee_id_fkey FOREIGN KEY (employee_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: time_log time_log_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.time_log
    ADD CONSTRAINT time_log_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE SET NULL;


--
-- Name: user_permissions_override user_permissions_override_column_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permissions_override
    ADD CONSTRAINT user_permissions_override_column_id_fkey FOREIGN KEY (column_id) REFERENCES public.journal_columns(id) ON DELETE CASCADE;


--
-- Name: user_permissions_override user_permissions_override_granted_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permissions_override
    ADD CONSTRAINT user_permissions_override_granted_by_id_fkey FOREIGN KEY (granted_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: user_permissions_override user_permissions_override_journal_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permissions_override
    ADD CONSTRAINT user_permissions_override_journal_id_fkey FOREIGN KEY (journal_id) REFERENCES public.journals(id) ON DELETE CASCADE;


--
-- Name: user_permissions_override user_permissions_override_user_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.user_permissions_override
    ADD CONSTRAINT user_permissions_override_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.users(id) ON DELETE CASCADE;


--
-- Name: users users_laboratory_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_laboratory_id_fkey FOREIGN KEY (laboratory_id) REFERENCES public.laboratories(id) ON DELETE SET NULL;


--
-- Name: weight_log weight_log_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weight_log
    ADD CONSTRAINT weight_log_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: weight_log weight_log_measured_by_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weight_log
    ADD CONSTRAINT weight_log_measured_by_id_fkey FOREIGN KEY (measured_by_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: weight_log weight_log_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.weight_log
    ADD CONSTRAINT weight_log_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- Name: workshop_log workshop_log_equipment_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workshop_log
    ADD CONSTRAINT workshop_log_equipment_id_fkey FOREIGN KEY (equipment_id) REFERENCES public.equipment(id) ON DELETE RESTRICT;


--
-- Name: workshop_log workshop_log_operator_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workshop_log
    ADD CONSTRAINT workshop_log_operator_id_fkey FOREIGN KEY (operator_id) REFERENCES public.users(id) ON DELETE RESTRICT;


--
-- Name: workshop_log workshop_log_sample_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.workshop_log
    ADD CONSTRAINT workshop_log_sample_id_fkey FOREIGN KEY (sample_id) REFERENCES public.samples(id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--


